language: node_js

node_js:
  - 10.15.0

cache:
  directories:
  - node_modules

git:
  depth: 3

script:
  - cp .env.example .env
  - jest --detectOpenHandles --forceExit --coverage --coverageReporters=text-lcov | coveralls && rm -rf ./coverage